# Global Setting for the Database
# PageSize, StartRID, etc..

MAX_RECORDS = 512 # 4096/8
MAX_COLUMNS = 64
MAXINT = 2**64 - 1
NUM_METAS = 3
PAGE_RANGE = 16
INDIRECTION_COLUMN = 0
RID_COLUMN = 1
SCHEMA_ENCODING_COLUMN = 2
BASE_RID = 3
TIMESTAMP_COLUMN = 4
BUFFEL_POOL_SIZE = 100
