# Global Setting for the Database
# PageSize, StartRID, etc..

MAX_RECORDS = 512 # 4096/8
MAX_COLUMNS = 64
MAXINT = 2**64 - 1
NUM_METAS = 7
PAGE_RANGE = 16
INDIRECTION_COLUMN = 0
RID_COLUMN = 1
SCHEMA_ENCODING_COLUMN = 2
BASE_RID = 3
STARTTIME_COLUMN = 4
LASTUPDATETIME_COLUMN = 5
UPDATETIME_COLUMN = 6
